# Generated by Django 3.0 on 2019-12-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.TextField(blank=True, max_length=45),
        ),
    ]
