# Generated by Django 3.0 on 2021-03-06 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20210306_0639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
