# Generated by Django 3.0 on 2019-12-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20191214_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='new_image',
        ),
        migrations.AddField(
            model_name='image',
            name='joy_image',
            field=models.ImageField(default='default.jpg', upload_to='image/'),
        ),
    ]
