# Generated by Django 3.0 on 2019-12-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20191214_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='joy_image',
            field=models.ImageField(default='default.jpg', upload_to='index/'),
        ),
    ]
